### PR TITLE
Added python3.8 support

### PR DESCRIPTION
**Pull request by Bchass**
#12 

First contribution to a project, thought I would take a swing at this one. Took `indent()` from 3.9 and created its own function so 3.8 would pass. 

Tox is passing with 3.8, 3.9, and 3.10:

Untitled

### CODE REVIEW

**Comment by zeddo123** [comment]
Thank you for contributing! All the changes look good to me. Before merging, could you please squash all the commits into a single one? (you can use an interactive rebase `git rebase -i HEAD~3`)

**Review by zeddo123 — APPROVED** [review]

**Comment by Bchass** [comment]
Sorry about that ! :sweat_smile: Did an accidental merge, but the commits should be all set now.

**Comment by zeddo123** [comment]
Not quite, now there's commits from the `plugin` branch in your PR. [here](https://github.com/squirrel-writer/squirrel/pull/13/commits)

A solution would be to `rebase` against master. (`git rebase master`)

**Comment by Bchass** [comment]
I'm not to sure if that fixed it? The branch is up to date after rebase

**Comment by zeddo123** [comment]
Yeah it's up to date, but it has commits that aren't part of the PR. And they would create conflicts and pollute the commit history.

**Comment by Bchass** [comment]
> Yeah it's up to date, but it has commits that aren't part of the PR. And they would create conflicts and pollute the commit history.
> 
> You can try dropping those commits from your branch with an interactive rebase (`git rebase -i`).

It might be easier to re-do the PR? I've been trying to revert the commits. When I rebase I just get:

Untitled

**Comment by zeddo123** [comment]
>When I rebase I just get:

Did you try give it the number of commits you want to rebase? For instance, if you want to rebase the last 3 commits you would do `git rebase -i HEAD~3`.

>It might be easier to redo the PR?

Of course as a last resort you could do that.

**Comment by Bchass** [comment]
> > When I rebase I just get:
> 
> Did you try give it the number of commits you want to rebase? For instance, if you want to rebase the last 3 commits you would do `git rebase -i HEAD~3`.
> 
Yes, I realized I was trying to squash downwards instead of upwards and that's where I went wrong. In the Intreset of time, I think it would be better to redo the PR becuase I haven't been able to get these commits to revert.

**Pull request closed without merging**
