### PR TITLE
Add PEP8 Linting to GitHub action

### PR DESCRIPTION
**Pull request by h-leth**
ref #14 

Let me know if it is useable
It's possible to add e.g `--ignore=E501` to flake if it's some checks you like to ignore.

### CODE REVIEW

**Comment by zeddo123** [comment]
`--ignore='F405 E501 W605' --per-file-ignores='__init__.py:F401 tests/*:F401'` I find that this configuration does not make the linting too annoying to deal with. It will probably throw you some (legitimate) linting error this time, if you have time fix them. So that I'll push them with the github action.

**Comment by h-leth** [comment]
👍🏻 I'll see if I can get it done tomorrow

**Review by zeddo123 — APPROVED** [review]

**Comment by h-leth** [comment]
Check it now.

Added `F403` to allow `from module import *`
Added `F811` to `tests/*` to "allow redefinition of unused variable" set in `fixtures.py`

**Comment by zeddo123** [comment]
Yeah it's working, except for `W504`, it should also be ignored.

**Comment by h-leth** [comment]
I'm getting an error when trying to run `watch -d`
```sh
2022-02-08 22:52:33 ERROR    Traceback (most recent call last):
2022-02-08 22:52:33 ERROR      File "/Users/hleth/.local/share/virtualenvs/squirrel-Rrl0w4p3/lib/python3.9/site-packages/daemonize.py", line 248, in start
2022-02-08 22:52:33 ERROR        self.action(*privileged_action_result)
2022-02-08 22:52:33 ERROR      File "/Users/hleth/PythonProjects/GitHub/squirrel/squirrel/commands/watch.py", line 105, in daemon
2022-02-08 22:52:33 ERROR        project_type = get_data_from_project_file()['project_type']
2022-02-08 22:52:33 ERROR    KeyError: 'project_type'
```

**Comment by zeddo123** [comment]
Yes, please. it's just a simple typo.

**Comment by h-leth** [comment]
done

**Pull request merged**
