### PR TITLE
Added GH Action to test using tox

### PR DESCRIPTION
**Pull request by RishiKumarRay**
#10

### CODE REVIEW

**Comment by zeddo123** [comment]
I'm not used to github actions. Do you think it is possible to have a more verbose output of `tox`? Because usually it shows all the tests that ran.
image

**Comment by RishiKumarRay** [comment]
@zeddo123 i am going to use the other way to build and test like as you have mentioned how to build locally , i will be using that for github actions

**Comment by zeddo123** [comment]
Yeah would probably have the same result now but we might add more commands to tox in the future.Could it be that the output of tox is only omitted when the all the tests are valid? and when it fails, it would display the regular output?

**Comment by RishiKumarRay** [comment]
@zeddo123  I tried looking at pytest but i think tox is better as its working as of now, let me just read about the output of tox then only i can tell you , meanwhile if you find anything please let me know , Thanks

**Comment by zeddo123** [comment]
I look at the `tox-gh-actions` repo and they recommand to add this section in `tox.ini`:
```yml
[gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310, mypy
```

**Comment by RishiKumarRay** [comment]
@zeddo123 yeah i saw this too

**Comment by RishiKumarRay** [comment]
@zeddo123  I saw a video there he pointed out whenever our tests will be successful it will print congratulations like this in the screenshots.

Screenshot from 2022-02-02 19-35-03

**Comment by RishiKumarRay** [comment]
@zeddo123 checkout this video https://www.youtube.com/watch?v=DhUpxWjOhME  , watch from time 18:34

**Comment by zeddo123** [comment]
That's the usual output of `tox`, when you run it locally. What I am interested in is the output of pytest inside `tox` which does not seem to be displayed.

**Comment by RishiKumarRay** [comment]
@zeddo123 i don't think it will be displayed , let me read if there is any way or let me know if you get something

**Comment by zeddo123** [comment]
I was able to make it work. You can checkout the github action [here](https://github.com/zeddo123/squirrel/pull/1). It turns out py3.8 is not supported.

**Comment by RishiKumarRay** [comment]
Yeah @zeddo123 this looks like it worked except for 3.8 , we can remove that

**Comment by RishiKumarRay** [comment]
But why we are not adding gh actions in tox ini like earlier you suggested ?

**Comment by RishiKumarRay** [comment]
@zeddo123 [gh-actions]
python =
    3.7: py37
    3.8: py38
    3.9: py39
    3.10: py310, mypy
Adding something like this , i read they were saying to add something like this.

**Comment by zeddo123** [comment]
Tbh I just tried to run `tox` without `tox-gh-actions` first and it works. I haven't given it much attention.

**Comment by RishiKumarRay** [comment]
@zeddo123  can you check this one i tried using gh tox , it works on versions 3.9 and above https://github.com/RishiKumarRay/squirrel/runs/5039303512?check_suite_focus=true

**Comment by zeddo123** [comment]
It still does not display the tox output correctly.
image

**Comment by RishiKumarRay** [comment]
check that link 
Screenshot from 2022-02-02 21-38-44

**Comment by RishiKumarRay** [comment]
@zeddo123 click on the arrow tox:39 the drop down will appear , see my screenshots

**Comment by zeddo123** [comment]
Sorry Yeah that works then.

**Comment by zeddo123** [comment]
Your master branch still have the old github action, you should probably rebase against your testing branch.

**Comment by RishiKumarRay** [comment]
@zeddo123 yeah i was just testing the gh action by making a new branch since it will increase the commits

**Comment by zeddo123** [comment]
>since it will increase the commits

You can always rebase and squash the unnecessary commits.

This seems to be much to more clean tho:
```yml
name: tox

on:
  - push
  - pull_request

jobs:
  tox:
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.10']
        os: ['ubuntu-latest']

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install tox
      run: pip install --upgrade tox virtualenv
    - name: run tox
      run: tox -e py
```
compared to yours
```yml

name: check
on:
  push:
  pull_request:
  schedule:
    - cron: "0 8 * * *"

jobs:
  test:
    name: test ${{ matrix.py }} - ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      fail-fast: false
      matrix:
        os:
          - Ubuntu
          
        py:
          - "3.10.0-rc.1"
          - "3.9"
          - "3.8"
          - "3.7"
          - "3.6"
    steps:
      - name: Setup python for test ${{ matrix.py }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.py }}
      - uses: actions/checkout@v2
      - name: Install tox-gh
        run: python -m pip install tox-gh
      - name: Setup test suite
        run: tox4 r -vv --notest
      - name: Run test suite
        run: tox4 r --skip-pkg-install
        env:
          PYTEST_ADDOPTS: "-vv --durations=10"
```

**Comment by RishiKumarRay** [comment]
@zeddo123 fine then which code you want , let me know i will make changes and add it to your PR , should i add your code of github actions?

**Comment by zeddo123** [comment]
I already closed mine, I just made it for testing. Easiest thing would be to update the github action with mine in your branch. Can you also add the badge in the `README.md` file?

**Comment by zeddo123** [comment]
LGTM thank you!
One thing, you still unnecessary commit that if I pulled your changes would pollute the commit history. In my opinion the best thing to do would be to run `git rebase -i HEAD~10` and squash the commits into a single one.

**Comment by RishiKumarRay** [comment]
@zeddo123 please check i have added the badge that will work after running the actions once.

**Comment by zeddo123** [comment]
> @zeddo123 please check i have added the badge that will work after running the actions once.

No, it's not being displayed correctly in the `README.md`.
image

**Comment by RishiKumarRay** [comment]
@zeddo123 let me check , i tested on testing branch of mine it was working

**Comment by RishiKumarRay** [comment]
Screenshot from 2022-02-02 22-32-40
see its working on mine @zeddo123

**Comment by zeddo123** [comment]
Okay, thank you again for taking the time to do this. I'll merge the changes

**Comment by RishiKumarRay** [comment]
@zeddo123 thanks , i see the badge too now after merging , just run the workflow manually once and it will show passed after that.

**Pull request merged**
