### PR TITLE
New Plugin Manager implementation

### PR DESCRIPTION
**Pull request by zeddo123**
The motivation of this PR is to improve the way we import plugins so that we are able to handle plugins that use third party modules correctly (e.g verify that the modules are available if not display a useful message to the user).

̶W̶i̶t̶h̶ ̶t̶h̶i̶s̶ ̶P̶R̶,̶ ̶t̶h̶e̶ ̶p̶l̶u̶g̶i̶n̶ ̶m̶a̶n̶a̶g̶e̶r̶ ̶w̶i̶l̶l̶ ̶e̶x̶p̶e̶c̶t̶ ̶p̶l̶u̶g̶i̶n̶s̶ ̶t̶o̶ ̶h̶a̶v̶e̶ ̶a̶ ̶`̶P̶l̶u̶g̶i̶n̶`̶ ̶c̶l̶a̶s̶s̶.̶ ̶T̶h̶e̶ ̶p̶l̶u̶g̶i̶n̶ ̶c̶l̶a̶s̶s̶ ̶w̶i̶l̶l̶ ̶a̶l̶s̶o̶ ̶p̶r̶o̶v̶i̶d̶e̶ ̶u̶s̶e̶f̶u̶l̶ ̶i̶n̶f̶o̶r̶m̶a̶t̶i̶o̶n̶ ̶a̶b̶o̶u̶t̶ ̶t̶h̶e̶ ̶p̶l̶u̶g̶i̶n̶ ̶(̶n̶a̶m̶e̶,̶ ̶d̶e̶s̶c̶r̶i̶p̶t̶i̶o̶n̶,̶ ̶e̶t̶c̶)̶.̶
̶`̶`̶`̶P̶y̶t̶h̶o̶n̶
̶c̶l̶a̶s̶s̶ ̶P̶l̶u̶g̶i̶n̶:̶
̶ ̶ ̶n̶a̶m̶e̶ ̶=̶ ̶.̶.̶.̶
̶ ̶ ̶d̶e̶s̶c̶r̶i̶p̶t̶i̶o̶n̶ ̶=̶ ̶.̶.̶.̶
̶ ̶ ̶r̶e̶q̶u̶i̶r̶e̶s̶ ̶=̶ ̶(̶ ̶'̶a̶n̶y̶ ̶n̶o̶n̶ ̶b̶u̶i̶l̶t̶i̶n̶ ̶p̶l̶u̶g̶i̶n̶'̶,̶ ̶)̶
̶
̶ ̶ ̶d̶e̶f̶ ̶g̶e̶t̶_̶c̶o̶u̶n̶t̶(̶f̶i̶l̶e̶s̶)̶ ̶-̶>̶ ̶i̶n̶t̶:̶
̶ ̶ ̶ ̶ ̶ ̶.̶.̶.̶
̶`̶`̶`̶
̶A̶n̶y̶ ̶m̶o̶d̶u̶l̶e̶ ̶t̶h̶a̶t̶ ̶i̶s̶ ̶d̶e̶c̶l̶a̶r̶e̶d̶ ̶i̶n̶ ̶`̶r̶e̶q̶u̶i̶r̶e̶s̶`̶ ̶w̶i̶l̶l̶ ̶b̶e̶ ̶l̶o̶a̶d̶ ̶g̶l̶o̶b̶a̶l̶l̶y̶ ̶a̶n̶d̶ ̶w̶i̶l̶l̶ ̶b̶e̶ ̶a̶v̶a̶i̶l̶a̶b̶l̶e̶ ̶t̶o̶ ̶`̶g̶e̶t̶_̶c̶o̶u̶n̶t̶`̶.̶ ̶A̶ ̶m̶o̶r̶e̶ ̶e̶x̶t̶e̶n̶s̶i̶v̶e̶ ̶e̶x̶a̶m̶p̶l̶e̶ ̶c̶a̶n̶ ̶b̶e̶ ̶f̶o̶u̶n̶d̶ ̶i̶n̶ ̶`̶p̶l̶u̶g̶i̶n̶_̶e̶x̶a̶m̶p̶l̶e̶.̶p̶y̶`̶.̶

# New changes

Plugins will have to include a `.yaml` config file that has all the metadata about the plugin (name, descriptions, etc) as well as any dependencies that are needed (there is a distinction between `pip` and `system` deps). Additionally, plugins will now be put in their own directories inside `squirrel/plugins`.

As before, `.py` modules of plugins will contain the `get_count` function.

### Example
```yaml
name: example
authors:
  - squirrel,<mail@mail.com>
description: description of the example plugin
version: 0.0.0
deps:
  sys:
    - command
  pip:
    - python_package
```

I̶'̶m̶ ̶t̶a̶g̶g̶i̶n̶g̶ ̶t̶h̶i̶s̶ ̶a̶s̶ ̶a̶ ̶d̶r̶a̶f̶t̶ so any suggestions are very welcomed :)

### CODE REVIEW

**Comment by zeddo123** [comment]
Hey @h-leth! Would love your input on this new plugin arch.

**Comment by h-leth** [comment]
Looks like a great way to minimize modules that have to be loaded global and only used in spesific plugins. Think I have to try and write a plugin to get a better hang on how it works.

I'll try to work out issue #1.
What´s best practice then, make a new branch based on this branch?

**Comment by zeddo123** [comment]
> What´s best practice then, make a new branch based on this branch?

Yeah probably, but best not depend a lot on this branch for now as I've been experiencing some failures of this design.

**Comment by zeddo123** [comment]
There's an issue with this implementation. I was not able to dynamically import the deps from `requires` globably so that they can be used without importing them; a simple solution would be to require plugins to import any libs inside `get_count()` which would be very ugly and not pythonic. A better solution would be separate the config of the plugin from the actual code of the plugin. Thus, we would have a `texcount.yaml` and a `texcount.py`. In the the `yaml` file, the plugin would declare any pip or system dependecies (we would check them before running the plugin) and `texcount.py` would be a normal python module.

**Comment by zeddo123** [comment]
@h-leth, I'm making the PR ready for review. I've made quite a lot of changes from what I first intended. It turns out it much simpler to separate plugins from the metadata that way we can check deps before importing the python module. Take a look when you have time, and give me your thoughts.

**Comment by h-leth** [comment]
Looks good as far as I understand. Much learning for me to read and try to understand whats going on.

We still have to install e.g `docx` in pyenv in advance? It just raises an error if its not present?

I miss the logging events to be written to `squirreld.log` and not just when `--debug watch` is ran.

```python
class PluginManager:

    def __init__(self, logger, project_type=''):
        self.logger = logger
        self.project_type = project_type
```
Add `logger` to `__init__` and change all `logger` to `self.logger`

**Comment by zeddo123** [comment]
> We still have to install e.g `docx` in pyenv in advance? It just raises an error if its not present?

Yeah because `docx` is not a general dependency, users will have to install it on their own.

I will sort out the logging part in another PR.

**Pull request merged**
